### ISSUE TITLE
Feature: Include Configuration in URL

### ISSUE THREAD

**Issue by BLACK4585** [jacobsjo/mc-datapack-map#11]
It would be very nice if you could store the current configuration like settings, selected/used datapacks and map position. The first and last one should be very simple via a JSON file you can store. For the selected DPs maybe it is possible to create one big ZIP file where everything is contained. Then there would also be the config file included.

**Comment by jacobsjo** [comment]
I think the easiest way to do this would be to store it in browser storage. In most desktop browsers (except firefox), it is also possible to store file access in storage (see the "Recently used" menu), so it would be easy to store a configuration including the used datapacks.

The only disadvantage of that would be that it remains in the browser and can't be shared. (But sharing a big ZIP file that includes multiple datapacks wouldn't be that great either...)

**Comment by BLACK4585** [comment]
For me, it wasn't really meant to share with others, just to store everything and also the DPs I used.
Personally, I would prefer having like a ZIP file with everything in it, but I totally understand you.
I really like this file access point, but since I'm using Firefox... 😞 

Since you would be able to save everything without the used resources, the stored config is half as useful, in my opinion.
So I would prefer a solution where everything is stored. But I would also appreciate it if you can store the raw config for now if this is easier for you or makes generally more sense.

**Comment by jacobsjo** [comment]
The issue I see with a big zip file is that it would be facilitating or encouraging the creation of "datapack-packs" and the redistribution of datapacks; possibly without the user even knowing that they redistribute the datapacks. That can lead to legal issues (i.e. the terralith license explicitly forbids redistrubition and inclusion in datapack-packs).

Another idea of configuration saving: Include the options in the URL for sharing or bookmarking specific configuations. Datapacks could be either opened automatically from the "Recently used" menu or prompted to be opened by the user. 

I also prefer Firefox, but unfortunately Firefox isn't great for web-apps like this that are dealing with file access.

**Comment by BLACK4585** [comment]
Yeah I really like your suggestion with the URL Parameters and the Recently Used menu or the notification by the browser to open the required DPs!

**Comment by jacobsjo** [comment]
implemented in #62
