### ISSUE TITLE
Seed Generator isn't working 

### ISSUE THREAD

**Issue by xreapurr** [jacobsjo/mc-datapack-map#14]
I added Terralith to the data pack and when I randomize a seed or add one in it doesn't have the map display according to the seed, it just stays at the default 0. I don't understand how to get the map to correspond to the seed input. If anyone can help me figure it out or explain how map works that would be great! Thank you!

**Comment by jacobsjo** [comment]
It works fine for me, adding the Terralith datapack and clicking the randomize seed button does refresh the map and generate a different biome layout each time. Manually inputting a seed and pressing enter also works.

Could you please specify exactly what you did and which datapack (version) you used?

**Comment by xreapurr** [comment]
that's so odd! Yeah, I have this https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/ and here is a screenshot of the one on my computer aswell, https://prnt.sc/jBTdTWILO4s_ 
So I am clicking the plus button and I use the open datapack.zip then I click the zip Terralith file, but nothing changes nor works for me.. :P I tried entering  -6977854745223960145 in the seed box but the map doesn't change and it reverts to 0 in the seed box.. hope that helps?

**Comment by jacobsjo** [comment]
Doing exactly that does work for me:
![image](https://github.com/jacobsjo/mc-datapack-map/assets/10163794/1a436f5a-ecd0-4cbb-9f1b-49a74875723f)

For troubleshooting, could you please specify which OS and browser you use and check the javascript console for error messages (i.e. Ctrl/Cmd+Shift+J in Chrome, Ctrl/Cmd+Shift+K in Firefox).

**Comment by xreapurr** [comment]
I use Opera Gx >.< However I redownloaded the zip and refreshed everything n it works now! Thank you for your help! :3
