### ISSUE TITLE
Datapack not loading

### ISSUE THREAD

**Issue by Happyperson3796** [jacobsjo/mc-datapack-map#19]
Previously I was able to load a certain datapack into this tool, but as of this week it no longer loads. The datapack is completely unchanged, it's the same file I've used in the past. It's about 16mb, if that's relevant. The biomes and structures will load into the search tab just fine, but nothing displayed on the map will change.

**Comment by jacobsjo** [comment]
It still works with the datapacks I tested with. I did some refactoring this week to the datapack loading logic to allow for the new 1.20.2 overlay packs, which could have introduced this issue.

For me to reproduce the issue, you need to provide more information. Can you tell me which datapack doesn't work? (If it is private feel free to send it to me on discord: `@jacobsjo`)

**Comment by jacobsjo** [comment]
Thanks! The issue was that there is a file called `overworld 2.json` directly inside the `minecraft` namespace. As spaces aren't allowed in ids that caused it to crash.

The site now simply ignores those invalid files again.
