### ISSUE TITLE
Can't identify structures with long names

### ISSUE THREAD

**Issue by robosoup2** [jacobsjo/mc-datapack-map#24]
I have no way of telling what each of these structures are, I can't widen the sidebar or copy the text even.
amazing tool btw, it's been so helpful and i love it, great work

![image](https://github.com/jacobsjo/mc-datapack-map/assets/50124081/1d8838be-faa5-4af8-bf06-10c36b5f7e88)

**Comment by jacobsjo** [comment]
There is now a tooltip when hovering elements of that list. Its also prefering to shink parts before a `/`, rather than the end.

Also note that datapacks can decide better (localized) names for their strutures, see https://github.com/jacobsjo/mc-datapack-map/wiki/Localization
