### ISSUE TITLE
[Suggestion] Seed "finder"

### ISSUE THREAD

**Issue by AlienXtream** [jacobsjo/mc-datapack-map#26]
a semi automated way to reroll seeds until a given criteria is met (e.g "mushroom island at 0,0", "desert at spawn", maybe also "structure less than distnace from spawn"). 
edit because "less than" and "greater than" symbols embeds code...

**Comment by jacobsjo** [comment]
So what you are looking for is basically cubiomes-viewer with datapack support. There is an issue there for that: Cubitect/cubiomes-viewer#229. I think that would make more sense than to implement seed finding here. 

Our re-implementations of worldgen aren't exactly optimized for speed, and generally javascript isn't well suited to this kind of calculations.
