### ISSUE TITLE
[Suggestion] Local world map.

### ISSUE THREAD

**Issue by AlienXtream** [jacobsjo/mc-datapack-map#28]
ability to load an existing world's data. multi version worlds may be a problem (e.g Etho's Letsplay world). the intent more being to allow more advanced biome/world gen mods to be processed. similar to that... Amidst? Amist? the original seed viewer one that someone made a forge mod compat and in game viewer thing for... 

this would allow additional "world presets" to be loaded from an existing world data and be able to map things like "Better Nether/Better End" dimensions (as well as other modded dimensions). more a longterm goal this one...

**Comment by jacobsjo** [comment]
That is quite out of scope of this tool. There are enough tools to display a map of a generated world, such as https://github.com/Querz/mcaselector or mini-map mods. I don't think there is a need to redo this here; not every tool needs to do everything.
