### ISSUE TITLE
Custom End Biomes Do Not Appear

### ISSUE THREAD

**Issue by catter1** [jacobsjo/mc-datapack-map#3]
I was testing out new biome colors for Nullscape biomes, but when uploading Nullscape to the site, no Nullscape biomes were to be found. I messed with the y-level slider a bit, but to no regard. I went in game with the exact same datapack copy, and biomes indeed generated, especially at the y-level I took the below screenshot it. Nullscape biomes have been set to appear as shades of purple.

Linked is the exact copy of [Nullscape 1.19.3](https://github.com/jacobsjo/mc-datapack-map/files/10945073/Nullscape_1.19.3_v1.2.1_BETA2.zip) I used. I should also note - the Nullscape biomes do appear in the "Search Biome" dropdown list.

![image](https://user-images.githubusercontent.com/63272345/224400749-a405b497-e1c1-46b9-9809-c1d309aafbdd.png)

**Comment by jacobsjo** [comment]
Since I'm not deploying to the website using a development version of deepslate with that fix in it, I'm closing this issue now.
