### ISSUE TITLE
Buried Treasures

### ISSUE THREAD

**Issue by yungieamongie** [jacobsjo/mc-datapack-map#65]
selecting "Buried Treasure" on the structure list and then trying to find any is pointless because it tells you to zoom in even more when you already zoomed in as much as you can

**Comment by jacobsjo** [comment]
[ I've removed the unproductive second paragraph ]

**Comment by russ1003** [comment]
This still not fixed?

**Comment by yungieamongie** [comment]
yes, still not fixed

**Comment by russ1003** [comment]
i wonder when

**Comment by jacobsjo** [comment]
You guys don't make me more inclined to fix it by your spam...
